language: python

    python:
        - "3.4"

    # services:
    #     - postgresql

    env:
        - DJANGO=1.11 # DB=postregs

    install:
        - pip install -r requirements.txt

    # before_script:
    #     -

    script:
        - python manage.py test
