# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170622_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog_posts/'),
        ),
    ]
