# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='code',
        ),
    ]
