# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 02:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0002_remove_command_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
