# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0004_auto_20170823_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='method',
            field=models.TextField(default='change'),
            preserve_default=False,
        ),
    ]
