# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0005_command_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='command',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.Library'),
        ),
    ]
