# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 09:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0006_auto_20180301_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('preview', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataFrames',
        ),
    ]
